adjust/gentoo-overlay

dev-python/carbon/files/carbon.initd2

Prepare header for upstreaming.
Package-Manager: portage-2.2.26

dev-python/carbon: update initscript

---

app-misc/logstash/logstash-1.5.4-r1.ebuild

And update copyright year
Package-Manager: portage-2.3.0

app-misc/logstash: remove extra enewuser arguments

---

.travis.yml
dev-util/ephemeralpg/metadata.xml

Updating travis config and adding a missing `metadata.xml` to fix current repo test failures, in preparation to other ebuild work. Please review and merge.

Fix failing tests

---

dev-perl/App-Sqitch/App-Sqitch-0.998.0-r1.ebuild

Package-Manager: Portage-2.3.6, Repoman-2.3.1

dev-perl/App-Sqitch: Add DBD-Pg as dep

---

dev-perl/App-Sqitch/App-Sqitch-0.998.0-r2.ebuild

Package-Manager: Portage-2.3.6, Repoman-2.3.1

dev-perl/App-Sqitch: add File-HomeDir dep

---

dev-db/aerospike-server-enterprise/aerospike-server-enterprise-4.1.0.1.ebuild

Add new openldap dep to aerospike

---

dev-qt/qtgui/qtgui-4.8.5-r100.ebuild
dev-qt/qtgui/qtgui-4.8.7-r100.ebuild

Package-Manager: Portage-2.3.40, Repoman-2.3.9

dev-qt: Fix x11-proto deps

---

net-analyzer/luigi/files/luigi-2.7.6.init
net-analyzer/luigi/luigi-2.7.6-r1.ebuild

configurable logfile and config file, save state across reboots

net-analyzer/luigi: revbump

---

app-admin/schaufel/metadata.xml
app-admin/schaufel/schaufel-9999.ebuild

Ebuild to make the latest schaufel head build.

Schaufel 9999

---

net-analyzer/postgresql_exporter/postgresql_exporter-0.1.0.ebuild

Not entirely sure how this worked up until now? :woman_shrugging:

net-analyzer/postgresql_exporter: group for fowners

---

net-analyzer/nmis/files/nmis-4.3.7c-dbi.patch

Package-Manager: Portage-2.3.76, Repoman-2.3.16

net-analyzer/nmis: Fix #311

---

sci-libs/scikits_learn/files/scikits_learn-0.20.2-fix-cdfast.patch
sci-libs/scikits_learn/scikits_learn-0.20.2.ebuild

See https://bugs.gentoo.org/630294
Package-Manager: Portage-2.3.83, Repoman-2.3.20

sci-libs/scikits_learn: Fix build

---

app-metrics/statsd_exporter/files/statsd_exporter-confd
app-metrics/statsd_exporter/files/statsd_exporter-initd
app-metrics/statsd_exporter/metadata.xml
app-metrics/statsd_exporter/statsd_exporter-0.14.1.ebuild

Required for https://github.com/adjust/infrastructure/issues/7708

app-metrics/statsd_exporter: first build

---

app-metrics/statsd_exporter/statsd_exporter-0.14.1.ebuild

As discussed in https://github.com/adjust/infrastructure/pull/7823

added KEYWORDS

---

sys-cluster/zookeeper-bin/zookeeper-bin-3.4.10.ebuild
sys-cluster/zookeeper-bin/zookeeper-bin-3.4.11.ebuild
sys-cluster/zookeeper-bin/zookeeper-bin-3.4.12.ebuild
sys-cluster/zookeeper-bin/zookeeper-bin-3.4.13.ebuild

Small change to reduce warnings from Zookeeper since home page is available in HTTPS (and I checked)

Reducing zookeeper warnings in repoman

---

net-analyzer/logdna-agent/logdna-agent-1.6.4-r1.ebuild

net-analyzer: quote variable per repoman

---

dev-db/bagger-data/bagger-data-0.3.ebuild

Package-Manager: Portage-3.0.6, Repoman-3.0.1

dev-db/bagger-data: Add pg12 compat

---

dev-python/asgiref/asgiref-1.1.2.ebuild
dev-python/coreschema/coreschema-0.0.4.ebuild
dev-python/croniter/croniter-0.3.26.ebuild
dev-python/datadog/datadog-0.16.0.ebuild
dev-python/django-compat/django-compat-1.0.15.ebuild
dev-python/django-hijack/django-hijack-2.1.4.ebuild
dev-python/facebook-sdk/facebook-sdk-9999.ebuild
dev-python/facebookads/facebookads-2.11.4.ebuild
dev-python/google-resumable-media/google-resumable-media-0.3.2.ebuild
dev-python/googleapis-common-protos/googleapis-common-protos-1.5.6.ebuild
dev-python/postmarker/postmarker-0.10.0.ebuild
dev-python/pytest-django/pytest-django-3.1.2.ebuild
dev-python/pytest/pytest-3.1.2.ebuild
dev-python/pyzabbix/pyzabbix-0.7.5.ebuild
dev-python/requests-mock/requests-mock-1.4.0.ebuild
dev-python/retry/retry-0.9.2.ebuild
dev-python/tinys3/tinys3-0.1.12.ebuild
profiles/package.unmask

Package-Manager: Portage-3.0.6, Repoman-3.0.1

dev-python: Python2 delendam est

---

README.md
repositories.xml

Hi
This PR:
* creates/adds the `repositories.xml` file to the overlay for a better experience/integration with the eselect `repository` tool.
* updates the `README.md` file to explain how to actually integrate the overlay with said tool.
Feel free to review and merge accordingly.

add repositories.xml file and update README

---

app-admin/bagger-tools/bagger-tools-9999.ebuild
app-admin/bagger-tools/files/schaufel_listener.confd
app-admin/bagger-tools/files/schaufel_listener.initd

Pre release feature: LISTENER_REPLICATION allows to toggle replication.

bagger-tools-9999: replication switch

---

sys-cluster/spark-bin/files/spark-history.confd
sys-cluster/spark-bin/files/spark-history.initd
sys-cluster/spark-bin/files/spark-mcd.confd
sys-cluster/spark-bin/files/spark-mcd.initd

Package-Manager: Portage-3.0.12, Repoman-3.0.2

sys-cluster/spark-bin: override start_pre() function and add checkpath.

---

sys-cluster/chronos-bin/files/chronos.confd
sys-cluster/chronos-bin/files/chronos.initd

Package-Manager: Portage-3.0.13, Repoman-3.0.2

sys-cluster/chronos-bin: add checkpath checks.

---

sys-cluster/mesos/files/mesos-agent.confd
sys-cluster/mesos/files/mesos-agent.initd
sys-cluster/mesos/files/mesos-master.confd
sys-cluster/mesos/files/mesos-master.initd

Package-Manager: Portage-3.0.13, Repoman-3.0.2

sys-cluster/mesos: add checkpath checks.

---

dev-db/bagger-data/bagger-data-0.4-r1.ebuild
dev-db/bagger-master/bagger-master-0.4-r1.ebuild

Bagger-master and bagger-data should be postgresql-13 compatible, this PR adds this feature.
Compatibility tested.

bagger: add postgres13 compatibility

---

net-analyzer/nmis/files/nmis-mre.patch
net-analyzer/nmis/nmis-4.3.7c-r1.ebuild

* create a diff to summarise his changes.
* eapply his changes to the nmis.pl Perl script.
Package-Manager: Portage-3.0.13, Repoman-3.0.2

net-analyzer/nmis: add mre changes to nmis ebuild.

---

app-admin/bagger-tools/bagger-tools-0.4-r1.ebuild
app-admin/bagger-tools/files/schaufel_listener-0.4-r1.confd
app-admin/bagger-tools/files/schaufel_listener-0.4-r1.initd

`LISTENER_REPLICATION` parameter is not used by default init script. This PR adds replication control from #499 to the current version.
@65278 @roa

app-admin/bagger-tools: add replication flag to the default init script

---

virtual/adjust-infrastructure/adjust-infrastructure-0.1.ebuild
virtual/adjust-infrastructure/metadata.xml

First stab at creating a meta package for all Perl modules required to use the infrastructure repository.
There are a few TODOS in there (e.g. LICENSE and HOMEPAGE), and the category + name of the package is meh, so feel free to suggest a better alternative.
If I have missed anything, please let me know and I can update  the DEPEND list.

first stab at infrastructure-meta ebuild

---

.github/CODEOWNERS

Restrict Pullrequest approval to adjust/sysadmins

Restrict Pullrequest approval to adjust/sysadmins

---

dev-db/postgresql/postgresql-10.16-r1.ebuild
dev-db/postgresql/postgresql-11.11-r1.ebuild
dev-db/postgresql/postgresql-12.6-r1.ebuild
dev-db/postgresql/postgresql-13.2-r1.ebuild
dev-db/postgresql/postgresql-9.6.21-r1.ebuild
sys-cluster/ceph/ceph-13.2.5-r5.ebuild

various qa fixes

---

profiles/package.mask

This is urgent. Schaufel 0.9 as a consumer will break production.

profiles/package.mask: mask schaufel-0.9

---

virtual/adjust-infrastructure/adjust-infrastructure-0.1-r1.ebuild

tweaked infrastructure ebuild to allow use of either rex or trex, and add some more deps.

virtual/adjust-infrastructure: tweak ebuild for forked rex

---

sys-apps/portage/portage-3.0.20-r1.ebuild

sys-apps/portage: set KEYWORDS='amd64'

---

dev-db/pgcenter/pgcenter-0.9.1.ebuild

Package-Manager: Portage-3.0.20, Repoman-3.0.3
as per title

dev-db/pgcenter: add RDEPEND on >=dev-lang/go-1.16

---

sys-cluster/mesos/files/mesos-1.10.0-maven-m2-directory-location.patch
sys-cluster/mesos/mesos-1.10.0.ebuild

sys-cluster/mesos: add patch to set maven m2 directory location to S.

---

eclass/mesos.eclass
sys-cluster/mesos/mesos-1.10.0-r1.ebuild

create mesos.eclass and inherit it in the ebuild.

sys-cluster/mesos: create eclass and inherit it in the ebuild.

---

dev-db/ajbool/ajbool-0.0.1.ebuild
dev-db/ajbool/ajbool-0.0.2.ebuild
dev-db/base36/base36-0.0.1.ebuild
dev-db/country/country-0.0.2.ebuild
dev-db/currency/currency-0.0.2.ebuild
dev-db/device_type/device_type-0.0.1.ebuild
dev-db/geoip2lookup/geoip2lookup-0.0.3.ebuild
dev-db/hashtypes/hashtypes-0.1.3.ebuild
dev-db/istore/istore-0.1.11.ebuild
dev-db/language/language-0.0.1.ebuild
dev-db/language/language-0.0.2.ebuild
dev-db/os_name/os_name-0.0.2.ebuild
dev-db/pglogical/pglogical-2.1.1.ebuild
dev-db/postgresql/metadata.xml
dev-db/postgresql/postgresql-9.6.22.ebuild
dev-db/roleman/roleman-0.3.0.ebuild
dev-libs/apache-arrow/apache-arrow-0.17.1-r2.ebuild
dev-libs/apache-arrow/apache-arrow-4.0.0-r1.ebuild
dev-python/fastapi/fastapi-0.63.0.ebuild
profiles/package.unmask

Fixes required for pkgcheck CI checks to go green.

*/*: pkgcheck CI fixes. [WIP]

---

app-metrics/carbonapi/carbonapi-0.15.2.ebuild
app-metrics/prometheus/prometheus-1.1.2.ebuild
app-metrics/prometheus/prometheus-1.4.1.ebuild
app-misc/go-carbon/go-carbon-0.15.6.ebuild
app-misc/logstash/logstash-1.5.4-r1.ebuild
app-misc/logstash/logstash-1.5.4-r2.ebuild
dev-python/certipy/certipy-0.1.3.ebuild
dev-python/python-json-logger/python-json-logger-0.1.4.ebuild
net-misc/calicoctl/metadata.xml

Fixes required for repoman CI checks to go green.

*/*: repoman CI fixes. [WIP]

---

app-metrics/postgresql_exporter/files/postgresql_exporter.confd
app-metrics/postgresql_exporter/files/postgresql_exporter.initd

* move command_args to init file.
* set USER variable in confd file.
* get user from USER variable in initd file.

app-metrics/postgresql_exporter: fixes.

---

sys-cluster/spark-bin/spark-bin-2.4.3-r1.ebuild

I was not sure if we need to bunp the minor or release verison

sys-cluster/spark-bin:Add missing relative symlinks

---

dev-db/aerospike-server-enterprise/aerospike-server-enterprise-4.9.0.36.ebuild
dev-db/aerospike-server-enterprise/aerospike-server-enterprise-5.6.0.15.ebuild

update aerospike ebuild to match the required deps

fix readline dependency on aerospike ebuilds

---

dev-db/bagger-data/bagger-data-0.5.ebuild
dev-db/bagger-master/bagger-master-0.5.ebuild

Tested to work with postgres-14 this morning.

bagger-{data,master}: postgres-14 compat

---

net-analyzer/zabbix-aerospike-plugin/files/aerospike_latency_items.sh
net-analyzer/zabbix-aerospike-plugin/files/aerospike_namespace_items.sh
net-analyzer/zabbix-aerospike-plugin/files/aerospike_stats_items.sh
net-analyzer/zabbix-aerospike-plugin/files/aerospike_xdr_items.sh
net-analyzer/zabbix-aerospike-plugin/zabbix-aerospike-plugin-3.0.0.ebuild

Adding these additional wrapping scripts will allow us to generate different items in zabbix with the same externalscript :smile:

aerospike-zabbix-plugin: Additional wrapping scripts

---

app-admin/trex/trex-1.6.0.4.ebuild

update trex ebuild to match the required deps
Fixes https://github.com/adjust/infrastructure/issues/15526

app-admin/trex: add missing deps

---

dev-util/runners-supervisor/files/runners-supervisor.confd
dev-util/runners-supervisor/files/runners-supervisor.initd
dev-util/runners-supervisor/files/runners-supervisor.sh

runners-supervisor: add support for labeling

---

dev-util/sonarqube-developer/files/configuration.patch
dev-util/sonarqube-developer/files/exit-codes.patch

sonarqube: Fix problem with badly formated patch

---

app-metrics/jmx_exporter/files/kafka_exporter.initd
app-metrics/jmx_exporter/jmx_exporter-0.16.1.ebuild

adding init.d file to jmx_exporter ebuild

app-metrics/jmx_exporter: add init.d file

---

dev-db/pgbackrest/files/pgbackrest.confd
dev-db/pgbackrest/files/pgbackrest.initd
dev-db/pgbackrest/pgbackrest-2.38.ebuild

Pgbackrest added a TLS server for remote backups in 2.37.
I found this feature useful, so I've written some glue for it.

Pgbackrest TLS server

---

app-admin/bagger-tools/bagger-tools-0.7.ebuild

Mea Culpa, forgot to add `dev-perl/Config-INI`.

bagger-tools-0.7:  add rdep dev-perl/Config-INI

---

app-metrics/schaufel_exporter/files/schaufel_exporter.confd
app-metrics/schaufel_exporter/files/schaufel_exporter.initd
app-metrics/schaufel_exporter/files/schaufel_exporter.pl
app-metrics/schaufel_exporter/metadata.xml
app-metrics/schaufel_exporter/schaufel_exporter-0.1.ebuild

schaufel_exporter is a script developed by felix to parse schaufel logs and create basic statistics to export to graphite and have nice grafana dashboards about schaufel performance. I refactored it to send data to our victorimetrics cluster and packaged the whole thing.

app-metrics/schaufel_exporter: package for schaufel log parser

---

app-metrics/postgresql_exporter/files/postgresql_exporter.confd

changing OS user to match db hba config, from postgresql_exporter to postgres

app-metrics/postgresql_exporter/files/postgresql_exporter.confd: changing user to match db hba config

---

dev-util/sonarqube-developer/files/conf
dev-util/sonarqube-developer/files/init
dev-util/sonarqube-developer/files/pidfile.patch
dev-util/sonarqube-developer/sonarqube-developer-8.9.8.54436.ebuild

Address pid comment in
https://github.com/adjust/infrastructure/issues/15448#issuecomment-1180103729

Sonarqube hotfix

---

app-admin/bagger-tools/bagger-tools-0.7-r1.ebuild

add support for adjust_server_error labeled partitions

bagger-tools-0.7-r1.ebuild: add revamp to support error tag

---

dev-db/postgresql/files/postgresql.init-9.3-r1

ref issue https://github.com/adjust/infrastructure/issues/17837

add read permission to allow pgbouncer to read from

---

net-analyzer/logdna-agent/logdna-agent-3.6.0.ebuild

Package-Manager: Portage-3.0.38.1, Repoman-3.0.3

net-analyzer/logdna-agent: bump rust dependency

---

net-analyzer/zabbix-aerospike-plugin/zabbix-aerospike-plugin-3.0.0.ebuild

Insrall in this ebuild was broken. this patch will make it work accordingly.

zabbix-aerospike-plugin-3.0.0: fix src_install function

---

dev-db/clickhouse/clickhouse-19.16.19.85-r1.ebuild
dev-db/timescaledb/timescaledb-1.2.1-r1.ebuild
sys-cluster/ceph/ceph-13.2.10.ebuild
sys-cluster/ceph/ceph-14.2.6.ebuild
www-apps/shiny-server/shiny-server-1.5.6.875.ebuild

Replace deprecated cmake utils eclass with cmake eclass

---

app-metrics/schaufel_exporter/files/schaufel_exporter.pl

Make presented hostname to prometheus passed through option

schaufel_exporter: make hostname dynamic through options

---

dev-libs/jemalloc/jemalloc-5.1.0.ebuild

Remove redis restriction to be installed with redis-7+

enable patched jemalloc to be used by redis-7+

---

net-misc/quagga/quagga-1.2.4.ebuild

ref: https://adjust.slack.com/archives/C033QGJ8WVD/p1738246975017969

Move {sys-devel → dev-build}/libtool

---

dev-db/postgresql/postgresql-14.4.ebuild

https://adjustcom.atlassian.net/browse/PE-3266

dev-db/posgresql: add python3.12 to v14.4
