- dev-perl/RedisFailover/RedisFailover-9999.ebuild
- dev-perl/Ruby-VersionManager/Ruby-VersionManager-9999.ebuild
dev-perl/yaml was renamed to dev-perl/YAML
=> updated the DEPEND and RDEPEND sections
Package-Manager: portage-2.2.26
> Fix dev-perl/YAML dependencies

- app-misc/karmabot-bin/metadata.xml
Lack of `metadata.xml` breaks tests not just for master branch, but also for all branches trying to fork from there (e.g. any new work), or trying to rebase on top of current master (e.g. in-progress work).
Please use `repoman commit` for committing your ebuild work to prevent such issues, and also please respect automated test results in case you forgot to use `repoman commit` :)
> app-misc/karmabot-bin: add missing metadata.xml

- app-admin/schaufel/schaufel-9999.ebuild
needed for libpq
Package-Manager: Portage-2.3.6, Repoman-2.3.1
> app-admin/schaufel: add postgresql as a dependency

- net-analyzer/nmis/nmis-4.3.7c.ebuild
With rrdtool-1.6.0 nmis fails to generate graphs, e.g:
(Unlike rrdtool-1.5.5 which works as expected)
```
18-Jan-2018 13:32:59,rrdDraw,,RRDTool type=mem-router, database=/path/to/database4/health/router/$router.rrd Graphing Error: invalid option -- 'interlace' options=--title $router - 48 hours from 16-Jan-2018 13:32:59 to 18-Jan-2018 13:32:59 --vertical-label % Mem. Util. --start 1516109579 --end 1516282379 --width 500 --height 100 --imgformat PNG --interlace DEF:MemUsedD=/path/to/database4/health/router/$router.rrd:MemoryUsedPROC:AVERAGE DEF:MemFreeD=/path/to/database4/health/router/$router.rrd:MemoryFreePROC:AVERAGE DEF:MemUsedM=/path/to/database4/health/router/$router.rrd:MemoryUsedIO:AVERAGE DEF:MemFreeM=/path/to/database4/health/router/$router.rrd:MemoryFreeIO:AVERAGE …
```
> net-analyzer/nmis: depend on <rrdtool-1.6

- www-apps/shiny-server/shiny-server-1.5.6.875.ebuild
Shouldn't be able to change its own config (what if somebody exploits shiny server).
> shiny-server: user shiny mustn't own shiny-server config

- dev-db/postgresql/postgresql-10.4-r71.ebuild
The single change here apart from the other ebuilds is the SLOT name and IUSE does not have cassert anymore as econf unconditionally calls --enable-cassert.
Revision is picked specifically to be smaller than 101 to prevent any
potential problems during dependency resolution.
Admittedly, suffixing the SLOT is not the optimal way to do this. In the
future we could use virtuals for more fine-grained install control. See
the relevant issue for more context. Ref: adjust/infrastructure#3345
> Add postgresql-10.4-r71 ebuild with -dbg SLOT suffix for cassert

- app-admin/bagger-tools/bagger-tools-9999.ebuild
- app-admin/bagger-tools/files/schaufel_listener.confd
- app-admin/bagger-tools/files/schaufel_listener.initd
- app-admin/bagger-tools/metadata.xml
An init script for listener.pl, an updated listen.pl (signal handler and more argv parsing).
The Init script allows generating new kafka consumers by creating a symlink, e.g.:
ln -s schaufel_listener schaufel_listener.callback_worker_reattributions
This PR is related to several tickets, amongst them:
https://github.com/adjust/infrastructure/issues/2889
https://github.com/adjust/infrastructure/issues/3719
> Bagger tools init

- dev-db/metabase-bin/files/metabase-server-start.sh
old version of script starts the wrong binary
> dev-db/metabase-bin: fix metabase-server-start.sh

- dev-qt/qtwebkit/metadata.xml
- dev-qt/qtwebkit/qtwebkit-4.8.5-r100.ebuild
- dev-qt/qtwebkit/qtwebkit-4.8.7-r100.ebuild
Removing gstreamer as current version is masked and we don't seem to be using it.
> dev-qt/qtwebkit: Qtwebkit removing gstreamer

- net-analyzer/clickhouse_exporter/clickhouse_exporter-9999.ebuild
- net-analyzer/clickhouse_exporter/files/clickhouse_exporter.confd
- net-analyzer/clickhouse_exporter/files/clickhouse_exporter.initd
- net-analyzer/clickhouse_exporter/metadata.xml
From https://github.com/f1yegor/clickhouse_exporter. Upstream has no releases so using head.
Custom init.d and conf.d scripts.
> net-analyzer/clickhouse_exporter: ebuild for git head

- app-admin/schaufel/files/schaufel.logrotate
- app-admin/schaufel/schaufel-0.6.ebuild
- app-admin/schaufel/schaufel-9999.ebuild
We might find this addition useful. The su thing will work for now, I think. It may become a problem when we let schaufel write to /dev/log
> Schaufel logrotate

- app-admin/bagger-tools/files/schaufel_listener-0.3.initd
Found the one bug in my deployment.
This will set producer threads as intended when using a config. And this only happened because the naming convention doesn't make it clear which value applies to consumers and which to producers.
> bagger-tools init: set producer jobs when using a config

- dev-db/postgresql/postgresql-10.9.ebuild
- dev-db/postgresql/postgresql-11.4.ebuild
> (Bug #571046)
Lifted from gentoos portage build dirs.
This apparently blocks efforts on the shards.
Ref: #279
> dev-db/postgresql/postgresql-{10.9,11.4}: don't delete libpg{port,comon}.a

- app-admin/bagger-tools/bagger-tools-0.3.ebuild
Turns out bagger-tools only install by accident on most of our systems.
ref: https://github.com/adjust/infrastructure/issues/5705
> bagger-tools-0.3: missing deps

- sys-cluster/hadoop-bin/hadoop-bin-3.2.0.ebuild
Package-Manager: Portage-2.3.80, Repoman-2.3.19
Signed-off-by: Patrick Lauer <patrick@gentoo.org>
> sys-cluster/hadoop-bin: Add openssl-compat dep

- sys-cluster/ceph/ceph-13.2.5-r5.ebuild
When trying to install ceph on new machine, compilation kept Werroring out due to some dependency on boost (im hazy on details) .
Patrick yak shaved it into working by removing spdk dependency
Posting this here for consistency. Discussion should be whether to replace r4 with this, or have second profile available.
> sys-cluster/ceph: Updated ceph 13 ebuild, removes spdk dependency

- app-metrics/statsd_exporter/files/statsd_exporter.confd-r1
- app-metrics/statsd_exporter/files/statsd_exporter.initd-r1
- app-metrics/statsd_exporter/statsd_exporter-0.14.1-r1.ebuild
Renames files to follow a more standard format
Adds 'command_args_extra' to default init commands
Fixes oversight in confd to follow the default disabling value in init script
> app-metrics/statsd_exporter: r1 for init fixes

- sys-cluster/mesos/mesos-1.10.0.ebuild
Disable this constraint as we want to install both the agent and the master on some servers.
> sys-cluster/mesos: drop REQUIRED_USE.

- dev-db/pgbackrest/pgbackrest-2.26.ebuild
Without this directory, archiving asynchronously does not work. Since it's only a list of "okay" files with no size, it practically lives on pagecache.
Found out the hard way when working with cephfs and huge wal throughput.
> dev-db/pgbackrest: add spooler directory for async-archiving

- sys-cluster/chronos-bin/files/chronos.initd
- sys-cluster/mesos/files/mesos-agent.initd
- sys-cluster/mesos/files/mesos-master.initd
- sys-cluster/spark-bin/files/spark-history.initd
- sys-cluster/spark-bin/files/spark-mcd.initd
The correct variable name is output_log and not stdout_log.
Excerpt from man openrc-run:
```
output_log: This is the path to a file or named pipe where the standard
output from the service will be redirected.
```
I noticed the typo whilst rewriting an init script.
Signed-off-by: Patrice Clement <patrice.clement@adjust.com>
> sys-cluster: fix a typo in the variable name.

- dev-libs/apache-arrow/apache-arrow-0.17.1-r1.ebuild
Initial fixes to apache-arrow ebuild.
Now passing some additional args to cmake for multiple compression types.
This _should_ be part of fixes for [https://github.com/adjust/infrastructure/issues/10897](url)
> dev-libs/apache-arrow: add cmakeargs for compression types

- dev-libs/apache-arrow/apache-arrow-0.17.1-r2.ebuild
dev-libs/apache-arrow has a DEPEND on dev-libs/rapidjson which can be satisfied with header files provided by sys-cluster/mesos (which is currently in use on some servers), so make either package satisfy the requirement from dev-libs/apache-arrow.
repoman complains about cmake-utils eclass being deprecated in favour of cmake eclass, so I have migrated that for now. Tested on local ~amd64 Gentoo Linux machine and is building fine.
Fix for #11262
> dev-libs/apache-arrow: fix rapidjson dep + cmake inherit

- README.md
replace travis-ci status badge with pkgcheck + RepoMan status badges on GitHub Actions
> Update status badge for GitHub Actions workflows

- dev-perl/Ruby-VersionManager/Ruby-VersionManager-0.1.ebuild
If you find yourself tinkering with the directory name in the `src_unpack` phase, simply inherit the `vcs-snapshot` eclass and enjoy life instead.
@xmhd @varilci
> dev-perl/Ruby-VersionManager: inherit vcs-snapshot eclass.

- sys-cluster/mesos/mesos-1.10.0.ebuild
fix some deps to satisfy qa
note: mesos package seems to fail currently (even before these changes - appears to require some SANDBOX_WRITE="foo" tweaks), will investigate further after this is merged.
> sys-cluster/mesos: fix maven dep + remove openjdk-bin dep

- virtual/adjust-infrastructure/adjust-infrastructure-0.2.ebuild
Small tweaks for the ebuild as a whole.
e.g. only depend on dev-perl/Rex-foo-bar if app-admin/rex is in use.
Default to app-admin/trex.
> virtual/adjust-infrastructure: small tweaks

- eclass/python-utils-r1.eclass
tldr; upstream is aggressive in removing compatible PYTHON_IMPL which leaves many of our machines without a working Python environment..... so now we fork python-utils-r1 and tweak PYTHON_IMPL to fix that.
> eclass/python-utils-r1: fork eclass for PYTHON_IMPL tweaks

- dev-db/postgresql/files/lock_partitions.patch
- dev-db/postgresql/metadata.xml
- dev-db/postgresql/postgresql-12.7.ebuild
- dev-db/postgresql/postgresql-13.3.ebuild
Work in progress: Finding the right tuning to avoid buffer mapping locks on seriously huge postgres instances.
> dev-db/postgresql: add hugelwlock useflag

- dev-db/postgresql/postgresql-9.6.22.ebuild
Closes: https://github.com/adjust/gentoo-overlay/issues/647
Package-Manager: Portage-3.0.20, Repoman-3.0.3
> dev-db/postgresql: delete pg-legacytimestamp in use_enable.

- sys-kernel/genkernel/files/genkernel-4.2.3-fetch_sqfs.patch
- sys-kernel/genkernel/genkernel-4.2.3.ebuild
As per title.
Genkernel supports squashfs images embedded in the initramfs (as this was designed for liveCD's), however there is currently no logic for fetching an image via network.
This PR adds a new parameter 'fetch_sqfs=foo" to be passed which will provide a uri to fetch the squashfs image from. startup_network is handled if this parameter is used, and there is a conditional added to the startup_network code for USE_SSHD, so that we don't call start_network twice.
> sys-kernel/genkernel: implement logic for fetching squashfs image via network

- dev-db/postgresql/files/lock_partitions.patch
Turns out some of our processes do allocate more than 200 lwlocks in parallel, if given enough buffer partitions.
To alleviate this issue, I've increased this constant.
> postgresql/fiels/lock_partitions.patch: increase number of max simultaneous lwlocks to 1000

- dev-python/jupyterhub/jupyterhub-1.1.0.ebuild
dev-python/oauth2 has been masked, see https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=80bf8350bb3a4f9934957a73a3eb630cc591239d.
Switch to dev-python/oauthlib as suggested in the package.mask message.
> dev-python/jupyterhub: switch from oauth2 to oauthlib.

- app-metrics/supervisord_exporter/files/supervisord_exporter
- app-metrics/supervisord_exporter/files/supervisord_exporter.py
- app-metrics/supervisord_exporter/metadata.xml
- app-metrics/supervisord_exporter/supervisord_exporter-0.0.1.ebuild
This package depend on node_exporter
It will dump a prometheus metric file about the running supervisord jobs cpu and memory consumption each 10seconds in /var/lib/node_exporter. Then, the node exporter will parse that file each for each scrape.
> adding supervisord_exporter ebuild

- acct-user/github_runner/github_runner-0.ebuild
Some applications (like vagrant) require a home directory to be
available.
@artemyevav @xmhd
> acct-user/github_runner: Add home to user

- dev-util/runners-supervisor/files/runners-supervisor.confd
- dev-util/runners-supervisor/files/runners-supervisor.initd
- dev-util/runners-supervisor/files/runners-supervisor.sh
- dev-util/runners-supervisor/runners-supervisor-0.1.ebuild
Initial config of `dev-util/runners-supervisor` package.
This package implements autoscaling solution on the gentoo server without using k8s or aws (see https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners#recommended-autoscaling-solutions). It's a bash script that creates, configures, updates and monitors self-hosted ephemeral github runners.
> runners-supervisor: initial config

- app-metrics/supervisord_exporter/files/supervisord_exporter.py
when a supervisord job is destroyed and restarted it will be affected another pid. In the 60 seconds window until supervisord jobs list is updated, the metric dump will try to access elements that doesn't exist anymore in the list. I added an additional check to make sure that the keys exist before trying to access.
> supervisord_exporter: bug fix

- dev-db/aerospike-server-tools/aerospike-server-tools-5.2.0.ebuild
> Fix typo in extension

- app-metrics/carbonapi/carbonapi-0.15.4.ebuild
Carbonapi offers a graphical support for generating graphs based on cairo lib. We do not use this as we interface carbon api all the time with grafana instead. 
This use flag will allow us to build carbonapi without cairo support from portage layer.
ref: https://github.com/go-graphite/carbonapi/blob/main/BUILD.md#build-instructions
> Add support for nocairo carbonapi build

- dev-db/aerospike-server-enterprise/files/aerospike.init
- dev-db/aerospike-server-enterprise/files/aerospike.init2
To prevent starting aerospike without it's index-on-disk mountpoints, we add the following checks in the init script.
related to adjust/infrastructure#16215
> aerospike: add missing mountpoint detection in pre checks

- app-metrics/kafka_exporter-bin/kafka_exporter-bin-1.4.2.ebuild
In keepdir, i think there was a typo in the logdir path. removed the extra `}`
> kafka_exporter-bin/kafka_exporter-bin-1.4.2.ebuild: wrong log dir

- app-admin/schaufel/schaufel-9999.ebuild
Libconfig 1.5 has a bug concerning its grammar (no comma before empty element in a list). 
To force all servers to bump libconfig on schaufel build, I've updated the runtime dep.
> Schaufel libconfig parser bug

- app-metrics/aerospike-prometheus-exporter/aerospike-prometheus-exporter-1.2.0.ebuild
- app-metrics/aerospike-prometheus-exporter/files/aerospike-prometheus-exporter.initd
Ebuild had some issues that didn't allow proper installation + missing ownership of certain directories change. 
Init script had a minor issues that prevented from starting the daemon.
related to adjust/infrastructure#17556
> aerospike-prometheus-exporter: fix ebuild and init script

- net-analyzer/logdna-agent/files/logdna.init
Init script was redirecting the stdout and stderr in a way that didn't allow us to see the logs of the daemon. I changed it to use the --stderr and --stdout options of the start-stop-daemon command. Now it works
> net-analyzer/logdna-agent/files/logdna.init: redirect stderr and stdout to logfile

- net-proxy/nutcrackers/nutcrackers-1.2.1.ebuild
- net-proxy/nutcrackers/nutcrackers-1.2.2.ebuild
EAPI 5 is no longer supported by autotools eclass
> net-proxy/nutcrackers: bump to EAPI=8

- eclass/linux-mod.eclass
Base gentoo repo eclasses are updated, EAPI 5 has been deprecated and some ebuilds depend on the new EAPI version.
Relevant changes:
- EAPI 8 doesn't use eutils
- check_vermagic is removed on upstream, and doesn't seem to be used on our ebuilds
- Remove support for EAPI < 4. Removed from upstream and also not used on our tree
- set_arch_to_portage -> set_arch_to_pkgmgr: same function, but name was changed in upstream
- Take advantage of compressed modules if supported by kernel configuration.
> eclass/linux-mod.eclass: backport EAPI 8 update

- net-misc/tyk-gateway-bin/files/tyk-gateway.initd
- net-misc/tyk-gateway-bin/tyk-gateway-bin-4.0.6.ebuild
Signed-off-by: Sassan <sassan.torabkheslat@adjust.com>
For security and performance purposes, we should jail Tyk Gateway Service to a non-root user.
if (for any reason) the tyk-gateway service is compromised, we lose everything, because it is running with root user privileges.
> Run tyk by nonroot user (#808)

- app-metrics/aerospike-prometheus-exporter/aerospike-prometheus-exporter-1.2.0-r1.ebuild
- app-metrics/aerospike-prometheus-exporter/files/aerospike-prometheus-exporter.initd
Fixing the username for aerospike-prometheus-exporter as it was incorrectly set to `prometheus-exporter` instead of `aerospike-prometheus-exporter`
> app-metrics/aerospike-prometheus-exporter/ fix username

- dev-db/pgtelemetry/pgtelemetry-1.0.0.ebuild
Add pg15 to the POSTGRES_COMPAT, so we can install dev-db/pgtelemetry beside postgrSQL 15.
> pgtelemetr - add pg15 to the POSTGRES_COMPAT

- eclass/python-utils-r1.eclass
This will fix emerge complaint about ebuilds using python3_12 as python implementation. 
Our eclass python-utils-r1 was not python3_12 aware.
> eclass/python-utils-r1.eclass: add python3_12 in python patterns

- dev-db/base36/base36-0.0.1.ebuild
- dev-db/country/country-0.0.2.ebuild
- dev-db/currency/currency-0.0.2-r1.ebuild
- dev-db/device_type/device_type-0.0.1.ebuild
- dev-db/hashtypes/hashtypes-0.1.3.ebuild
- dev-db/istore/istore-0.1.11.ebuild
- dev-db/os_name/os_name-0.0.2.ebuild
dev-db/istore: add postgresql-15 compat
dev-db/hashtypes: add postgresql-15 compat
dev-db/device_type: add postgresql-15 compat
dev-db/currency: add postgresql-15 compat
dev-db/country: add postgresql-15 compat
dev-db/base36: add postgresql-15 compat
dev-db/os_name: add postgresql-15 compat
> Add postgresql 15 compat to postgresql extension packages

- app-metrics/twemproxy_exporter/files/nutcracker_exporter.confd
- app-metrics/twemproxy_exporter/files/nutcracker_exporter.initd
- app-metrics/twemproxy_exporter/files/nutcracker_socket_exporter.confd
- app-metrics/twemproxy_exporter/files/nutcracker_socket_exporter.initd
- app-metrics/twemproxy_exporter/metadata.xml
- app-metrics/twemproxy_exporter/twemproxy_exporter-0.1.0.ebuild
Create twemproxy exporter for prometheus to export nutcracker (twemproxy) stats from TCP port 12 ( nutcracker port case ) and port 146 ( nutcracker socket case ) to prometheus for better monitoring
> create nutcracker exporter for prometheus

- app-admin/bagger-tools/files/schaufel_listener-0.3.initd
- app-admin/bagger-tools/files/schaufel_listener-0.4.initd
- app-admin/bagger-tools/files/schaufel_listener-0.5.initd
- app-admin/bagger-tools/files/schaufel_listener-0.7.initd
REPLICATION option was missing from being handled in the init script, it drove me crazy because i didn't assume at all that the issue was there.
> app-admin/schaufel: add missing replication option in init script

- eclass/python-utils-r1.eclass
Adding support for python3.13 as it currently breaks without it.
> eclass/python-utils-r1.eclass: add support for python3.13

- dev-db/pg_repack/pg_repack-19062024.ebuild
This ebuild is pinned to the following upstream commit: https://github.com/reorg/pg_repack/tree/3edf5b3df04dff792e693ff899b33de2e4fad859
> [PE-1307]: Custom ebuild for pg_repack

- app-admin/logstash-bin/logstash-bin-6.8.15.ebuild
Manual installation and slack [discussion](https://adjust.slack.com/archives/G01N6QY9NV7/p1737539374850759) for tracking.
```
emerge --pretend app-admin/logstash-bin
Local copy of remote index is up-to-date and will be used.
These are the packages that would be merged, in order:
Calculating dependencies | * ERROR: sys-libs/glibc-2.27-r666::adjust failed (depend phase):
*   prefix: EAPI 6 not supported
*
* Call stack:
*                ebuild.sh, line 632:  Called source '/var/db/repos/adjust/sys-libs/glibc/glibc-2.27-r666.ebuild'
*   glibc-2.27-r666.ebuild, line   6:  Called inherit 'prefix' 'eutils' 'versionator' 'toolchain-funcs' 'flag-o-matic' 'gnuconfig' 'multilib' 'systemd' 'multiprocessing'
*                ebuild.sh, line 312:  Called __qa_source …
```
> upgrade the logstash EAPI version

- dev-python/python-consul/python-consul-1.1.0-r1.ebuild
Add supported python versions and rename tornado as the portage tree requires
> python-consul: bump version

- app-metrics/keepalived-exporter/keepalived-exporter-1.4.0.ebuild
there's a small missing part for ebuild file in order to install go dependency
> PE-3145: add network-sandbox setting to an ebuild file

- dev-libs/jemalloc/jemalloc-5.1.0.ebuild
```
tr-backend-8 ~ # emerge --info '=dev-libs/jemalloc-5.1.0::adjust
> '
* ERROR: dev-libs/jemalloc-5.1.0::adjust failed (depend phase):
*   autotools: EAPI 6 not supported
*
* Call stack:
*               ebuild.sh, line 632:  Called source '/var/db/repos/adjust/dev-libs/jemalloc/jemalloc-5.1.0.ebuild'
*   jemalloc-5.1.0.ebuild, line   6:  Called inherit 'autotools' 'toolchain-funcs' 'multilib-minimal'
*               ebuild.sh, line 312:  Called __qa_source '/var/db/repos/gentoo/eclass/autotools.eclass'
*               ebuild.sh, line 123:  Called source '/var/db/repos/gentoo/eclass/autotools.eclass'
*        autotools.eclass, line  31:  Called die
* The specific snippet of code:
*   	*) die "${ECLASS}: EAPI ${EAPI:-0} not supported" ;;
*
* If you need support, post the output of `emerge …
```
> PE-3622: Fix jemalloc package to install on tr-backend-8 server

- app-admin/superlance/superlance-2.0.0.ebuild
To fix the following error, when OS is using newer versions of PYTHON_TARGETS:
```
!!! All ebuilds that could satisfy ">=dev-python/setuptools-78.1.0[python_targets_python3_10(-)?]" have been masked.
!!! One of the following masked packages is required to complete your request:
- dev-python/setuptools-79.0.1::gentoo (masked by: corruption)
- dev-python/setuptools-79.0.0::gentoo (masked by: corruption)
- dev-python/setuptools-78.1.1::gentoo (masked by: corruption)
- dev-python/setuptools-78.1.0::gentoo (masked by: corruption)
(dependency required by "app-admin/superlance-2.0.0::adjust" [ebuild])
(dependency required by "app-admin/superlance" [argument])
```
More context here:
https://adjust.slack.com/archives/G01N6QY9NV7/p1745492715881439
> PE-3831: Fix the python compatibility issue when python target set to  python3.11, python3.12
